### ISSUE TITLE
Megamenu Incorrectly Aligned in Firefox 41.0.2

### ISSUE THREAD

**Issue by naptash** [wet-boew/theme-gcwu-fegc#229] opened 2015-10-21 21:06 UTC
Windows 7 Enterprise, SP1
Firefox 41.0.2 

The megamenu navigation isn't left-aligned. It starts almost directly underneath the Maple Leaf. Might be an issue with the H2 Topics Menu (I was playing around and hide the position:absolute from the #mb-pnl .srch-pnl label, #mb-pnl h3, #wb-bc h2, #wb-glb-mn h2, #wb-info h2, #wb-lng h2, #wb-sec h2, #wb-sm h2, #wb-srch h2, #wb-srch label, .cal-days td ul, .wb-fnote dt, .wb-inv, .wb-invisible, .wb-show-onfocus, .wb-sl { (theme.min.css:6))

**Comment by LaurentGoderre** [comment] 2015-10-22 12:56
duplicate of #189

**Closed by LaurentGoderre** 2015-10-22 12:56 UTC
